version: "3.7"

services:
  api:
    platform: linux/x86-64
    build:
      context: .
      dockerfile: Dockerfile
    image: naum/api:1.0.0
    container_name: api
    ports:
      - 3000:3000
    restart: always
    volumes:
      - $HOME/api_logs:/api/logs